[package]
name = "tonic_rust"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
tonic = "0.10"
tonic-reflection = "0.10"
prost = "0.12"

[dependencies.tokio]
version = "1"
features = ["full"]

[build-dependencies]
tonic-build = "0.10"
